### PR TITLE
fixing close curly bracket error

### PR DESCRIPTION
**Pull request by Joilnen**
getting compilation error in linux

### CODE REVIEW

**Comment by paroj** [comment]
my guess would be that you have a newer glslang and thus have to comment in this:
https://github.com/OGRECave/ogre/blob/7fc8890f8f115a33f7b7f8d8ba546ba257435176/PlugIns/GLSLang/src/OgreGLSLang.cpp#L110

**Comment by Joilnen** [comment]
where this is declared TBuiltInResource ?

**Comment by Joilnen** [comment]
Redoing this better

**Comment by Joilnen** [comment]
Yes for glslang 11 it doesn't compile without that last parameter before limits, but it works for glslang 8.x

**Pull request closed without merging**
