### PR TITLE
Correction on IOS configuration

### PR DESCRIPTION
**Pull request by arkeon7**
Correct a mistake in cmake scripts

### CODE REVIEW

**Comment by paroj** [comment]
why do you think this is a mistake?

**Comment by arkeon7** [comment]
Because it was not working last time I build on IOS, and this change corrected it.
also there is a old port about it https://forums.ogre3d.org/viewtopic.php?t=76067

**Comment by paroj** [comment]
that report was about ANDROID and led to the code as it is now. AFAIK xcode is supposed to replace  the `$(` stuff. If you grep for it, we have it all over the CMake files.

**Comment by arkeon7** [comment]
Ok weird last time I've updated xcode it lead to an error. I don't remember well when I did this change, maybe xcode just finally took it...

**Pull request closed without merging**
