### PR TITLE
Simplifying use of ApplicationContext framework

### PR DESCRIPTION
**Pull request by Joilnen**
Proposal
try to avoid internal root exposing to user application as much as possible, no break the actual interface,
changed the Bootstrap.cpp tutorial if it is accept I change the rest

### CODE REVIEW

**Comment by paroj** [comment]
> try to avoid internal root exposing to user application as much as possible

why do you think this is beneficial? The Root object provides access to some important functions like the WorkQueue. Also it is a Singleton, so it is not really hidden..

**Comment by paroj** [comment]
also you accidentally reverted some recent changes in master

**Comment by JoilnenLeite** [comment]
> > try to avoid internal root exposing to user application as much as possible
> 
> why do you think this is beneficial? The Root object provides access to some important functions like the WorkQueue. Also it is a Singleton, so it is not really hidden..

My intention is avoid to expose root as much as possible, and to leave only ScanaManager as point of interaction with Ogre less failing points, the other features from Root I think to wrapper the in ApplicationContext, and made aplications created with this framework smaller and easier.

**Comment by Joilnen** [comment]
> also you accidentally reverted some recent changes in master

My intention is avoid to expose root as much as possible, and to leave only ScanaManager as point of interaction with Ogre less failing points, the other features from Root I think to wrapper the in ApplicationContext, and made aplications created with this framework smaller and easier.

**Pull request closed without merging**
